import React from 'react';
import { ResidentData } from '../types';
import { FileWarning, Printer } from 'lucide-react';

interface Props {
  residents: ResidentData[];
  month: string;
  onClose: () => void;
}

export const DeficiencyReport: React.FC<Props> = ({ residents, month, onClose }) => {
  
  const groupedIssues: Record<string, ResidentData[]> = {};

  residents.forEach(r => {
    if (r.compliance.issues.length > 0) {
      r.compliance.issues.forEach(issue => {
        // Normalize issue titles
        let key = issue.replace(/\(.*\)|`.+`|:.*/, '').trim();
        if (key.includes("Indication")) key = "Indication Review";
        if (key.includes("GDR")) key = "Manual GDR Review";
        if (key.includes("care plan")) key = "Care Plan Missing";
        if (key.includes("behavior monitoring")) key = "Behavior Monitoring";
        if (key.includes("psychiatry")) key = "Psychiatry Consult/Order";

        if (!groupedIssues[key]) {
          groupedIssues[key] = [];
        }
        // Avoid adding duplicate residents under the same general key
        if (!groupedIssues[key].find(res => res.mrn === r.mrn)) {
            groupedIssues[key].push(r);
        }
      });
    }
  });

  const sortedGroupKeys = Object.keys(groupedIssues).sort();

  const handleDownload = () => {
    const content = document.getElementById('deficiency-report-modal')?.innerHTML;
    if (!content) return;
    
    // Remove the fixed positioning from the modal shell for the static report
    const cleanContent = content
      .replace(/fixed inset-0.*?z-40/, 'relative mx-auto my-8')
      .replace(/max-h-\[90vh\]/, 'min-h-screen')
      .replace(/overflow-y-auto/, 'overflow-visible');

    const html = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>Deficiency Report - ${month}</title><script src="https://cdn.tailwindcss.com"></script><script>tailwind.config={theme:{extend:{colors:{primary:'#0b4ea2',secondary:'#0a3f85',bg:'#f6f8fc'}}}}</script><style>@media print{@page{margin:0.5in}.no-print-in-modal{display:none!important}}</style></head><body class="bg-slate-100 p-8 print:p-0 print:bg-white">${cleanContent}<div class="text-center mt-8 text-slate-400 text-xs no-print-in-modal">Generated by GDR Compliance Tool</div></body></html>`;
    
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Deficiency_Report_${month}.html`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div id="deficiency-report-modal" className="fixed inset-0 z-40 flex items-center justify-center bg-slate-900/50 backdrop-blur-sm p-4 no-print">
      <div className="bg-white w-full max-w-5xl rounded-2xl shadow-2xl flex flex-col max-h-[90vh]">
        
        {/* Header */}
        <div className="bg-slate-50 p-4 border-b border-slate-200 flex justify-between items-center print:hidden no-print-in-modal">
            <div className="flex items-center gap-3">
                <FileWarning className="w-6 h-6 text-red-600"/>
                <div>
                    <h3 className="font-bold text-slate-800 text-lg">Deficiency Report</h3>
                    <p className="text-sm text-slate-500">For Review Period: {month}</p>
                </div>
            </div>
            <div className="flex items-center gap-2">
                 <button 
                    onClick={handleDownload}
                    className="flex items-center gap-2 px-4 py-2 bg-slate-700 hover:bg-slate-800 text-white rounded-lg font-bold text-sm transition-colors shadow-sm"
                >
                    <Printer className="w-4 h-4" /> Download Printable Report
                </button>
                <button onClick={onClose} className="text-slate-400 hover:text-slate-600 font-bold text-2xl ml-2">✕</button>
            </div>
        </div>

        {/* Report Content */}
        <div className="p-6 overflow-y-auto">
            {/* Print Header */}
            <div className="hidden print:block mb-8 border-b border-black pb-4">
                <h1 className="text-2xl font-bold text-black">GDR & Psychotropic Deficiency Report</h1>
                <p className="text-sm text-gray-600">Review Month: {month} | Generated: {new Date().toLocaleString()}</p>
            </div>
          
            {sortedGroupKeys.length === 0 ? (
                <div className="text-center py-12 text-slate-400">
                    <p>No compliance issues found for this period.</p>
                </div>
            ) : (
                <div className="space-y-8">
                    {sortedGroupKeys.map(issueKey => (
                        <div key={issueKey} className="print:break-inside-avoid">
                            <h2 className="text-base font-bold text-red-700 bg-red-50 border border-red-200 rounded-t-lg px-4 py-2 print:text-black print:bg-gray-200 print:border-black">
                                {issueKey}
                            </h2>
                            <div className="border border-t-0 border-slate-200 rounded-b-lg overflow-hidden print:border-black">
                                <table className="w-full text-left text-sm">
                                    <thead className="bg-slate-50 text-xs uppercase text-slate-500 print:bg-white print:border-b print:border-black">
                                        <tr>
                                            <th className="px-4 py-2 w-1/3">Resident</th>
                                            <th className="px-4 py-2">Location</th>
                                            <th className="px-4 py-2">Details</th>
                                        </tr>
                                    </thead>
                                    <tbody className="divide-y divide-slate-100 print:divide-black">
                                        {groupedIssues[issueKey].map(resident => (
                                            <tr key={resident.mrn} className="print:break-inside-avoid">
                                                <td className="px-4 py-2 align-top">
                                                    <div className="font-medium text-slate-800">{resident.name}</div>
                                                    <div className="text-xs text-slate-400">MRN: {resident.mrn}</div>
                                                </td>
                                                <td className="px-4 py-2 align-top text-slate-600">
                                                    {resident.unit} / {resident.room}
                                                </td>
                                                <td className="px-4 py-2 align-top text-xs text-slate-500">
                                                    {resident.compliance.issues.join('; ')}
                                                </td>
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    ))}
                </div>
            )}
        </div>

      </div>
    </div>
  );
};
